#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <variant>
#include <utility>

class SkinDatabase {
public:
	class PetsInfo {
	public:
		const char* modelName;
		const char* skinName;
		std::variant<std::int32_t, std::pair<std::int32_t, std::int32_t>> skinCount{ 1 };
	};

	// PetModelName, PetName, PetSkinCount(manual update)
	std::vector<PetsInfo> pets{
		{ "PetDsSwordGuy",		"Abyssia",			std::make_pair(1, 21)},
		{ "PetAoShin",			"Ao Shin",			std::make_pair(1, 51)},
		{ "PetBunny",			"Bun Bun",			std::make_pair(1, 33)},
		{ "PetPupDragon",		"Bungo",			std::make_pair(1, 18)},
		{ "PetBaron",			"Baron",			std::make_pair(3, 33)},
		{ "petbat",				"Bat",				std::make_pair(3, 33)},
		{ "PetBellSwayer",		"Bell Swayer",		std::make_pair(1, 21)},
		{ "PetJawDragon",		"Burno",			std::make_pair(1, 33)},
		{ "PetChibiAatrox",		"Chibi Aatrox",		std::make_pair(1, 5)},
		{ "PetChibiAkshan",		"Chibi Akshan",		std::make_pair(1, 5)},
		{ "PetChibiAlistar",	"Chibi Alistar",	std::make_pair(1, 5)},
		{ "PetChibiAnivia",		"Chibi Anivia",		std::make_pair(1, 5)},
		{ "PetChibiAphelios",	"Chibi Aphelios",	std::make_pair(1, 5)},
		{ "PetChibiAsol",		"Chibi Aurelion Sol",std::make_pair(1, 5)},
		{ "PetChibiAhri",		"Chibi Ahri",		std::make_pair(1, 5)},
		{ "PetChibiAmumu",		"Chibi Amumu",		std::make_pair(1, 5)},
		{ "PetChibiAzir",		"Chibi Azir",		std::make_pair(1, 5)},
		{ "PetChibiAkali",		"Chibi Akali",		std::make_pair(1, 5)},
		{ "PetChibiAnnie",		"Chibi Annie",		std::make_pair(1, 5)},
		{ "PetChibiAshe",		"Chibi Ashe",		std::make_pair(1, 5)},
		{ "PetChibiBard",		"Chibi Bard",		std::make_pair(1, 5)},
		{ "PetChibiBlitzcrank",	"Chibi Blitzcrank",	std::make_pair(1, 5)},
		{ "PetChibiBrand",		"Chibi Brand",		std::make_pair(1, 5)},
		{ "PetChibiBraum",		"Chibi Braum",		std::make_pair(1, 5)},
		{ "PetChibiBriar",		"Chibi Briar",		std::make_pair(1, 5)},
		{ "PetChibiCaitlyn",	"Chibi Caitlyn",	std::make_pair(1, 5)},
		{ "PetChibiCamille",	"Chibi Camille",	std::make_pair(1, 5)},
		{ "PetChibiCassiopeia",	"Chibi Cassiopeia",	std::make_pair(1, 5)},
		{ "PetChibiChoGath",	"Chibi Cho'Gath",	std::make_pair(1, 5)},
		{ "PetChibiCorki",		"Chibi Corki",		std::make_pair(1, 5)},
		{ "PetChibiDarius",		"Chibi Darius",		std::make_pair(1, 5)},
		{ "PetChibiDiana",		"Chibi Diana",		std::make_pair(1, 5)},
		{ "PetChibiDrMundo",	"Chibi Dr. Mundo",	std::make_pair(1, 5)},
		{ "PetChibiDraven",		"Chibi Draven",		std::make_pair(1, 5)},
		{ "PetChibiEkko",		"Chibi Ekko",		std::make_pair(1, 5)},
		{ "PetChibiElise",		"Chibi Elise",		std::make_pair(1, 5)},
		{ "PetChibiEzreal",		"Chibi Ezreal",		std::make_pair(1, 5)},
		{ "PetChibiFiora",		"Chibi Fiora",		std::make_pair(1, 5)},
		{ "PetChibiFizz",		"Chibi Fizz",		std::make_pair(1, 5)},
		{ "PetChibiGalio",		"Chibi Galio",		std::make_pair(1, 5)},
		{ "PetChibiGaren",		"Chibi Garen",		std::make_pair(1, 5)},
		{ "PetChibiGnar",		"Chibi Gnar",		std::make_pair(1, 5)},
		{ "PetChibiGragas",		"Chibi Gragas",		std::make_pair(1, 5)},
		{ "PetChibiGraves",		"Chibi Graves",		std::make_pair(1, 5)},
		{ "PetChibiGwen",		"Chibi Gwen",		std::make_pair(1, 5)},
		{ "PetChibiHeimerdinger","Chibi Heimerdinger",std::make_pair(1, 5)},
		{ "PetChibiIllaoi",		"Chibi Illaoi",		std::make_pair(1, 5)},
		{ "PetChibiIrelia",		"Chibi Irelia",		std::make_pair(1, 5)},
		{ "PetChibiJanna",		"Chibi Janna",		std::make_pair(1, 5)},
		{ "PetChibiJarvanIV",	"Chibi Jarvan IV",	std::make_pair(1, 5)},
		{ "PetChibiJax",		"Chibi Jax",		std::make_pair(1, 5)},
		{ "PetChibiJayce",		"Chibi Jayce",		std::make_pair(1, 5)},
		{ "PetChibiJhin",		"Chibi Jhin",		std::make_pair(1, 5)},
		{ "PetChibiJinx",		"Chibi Jinx",		std::make_pair(1, 5)},
		{ "PetChibiKaiSa",		"Chibi Kai'Sa",		std::make_pair(1, 5)},
		{ "PetChibiKarma",		"Chibi Karma",		std::make_pair(1, 5)},
		{ "PetChibiKarthus",	"Chibi Karthus",	std::make_pair(1, 5)},
		{ "PetChibiKassadin",	"Chibi Kassadin",	std::make_pair(1, 5)},
		{ "PetChibiKatarina",	"Chibi Katarina",	std::make_pair(1, 5)},
		{ "PetChibiKayle",		"Chibi Kayle",		std::make_pair(1, 5)},
		{ "PetChibiKennen",		"Chibi Kennen",		std::make_pair(1, 5)},
		{ "PetChibiLeeSin",		"Chibi Lee Sin",	std::make_pair(1, 5)},
		{ "PetChibiLux",		"Chibi Lux",		std::make_pair(1, 5)},
		{ "petchibilulu",		"Chibi Lulu",		std::make_pair(1, 5)},
		{ "PetChibiMissFortune","Chibi Miss Fortune",std::make_pair(1, 5)},
		{ "PetChibiMalfite",	"Chibi Malphite",	std::make_pair(1, 5)},
		{ "PetChibiMalzahar",	"Chibi Malzahar",	std::make_pair(1, 5)},
		{ "PetChibiMaokai",		"Chibi Maokai",		std::make_pair(1, 5)},
		{ "PetChibiMasterYi",	"Chibi Master Yi",	std::make_pair(1, 5)},
		{ "PetChibiMordekaiser","Chibi Mordekaiser",std::make_pair(1, 5)},
		{ "PetChibiNami",		"Chibi Nami",		std::make_pair(1, 5)},
		{ "PetChibiNeeko",		"Chibi Neeko",		std::make_pair(1, 5)},
		{ "PetChibiMorgana",	"Chibi Morgana",	std::make_pair(1, 5)},
		{ "PetChibiNautilus",	"Chibi Nautilus",	std::make_pair(1, 5)},
		{ "PetChibiNidalee",	"Chibi Nidalee",	std::make_pair(1, 5)},
		{ "PetChibiNunu",		"Chibi Nunu",		std::make_pair(1, 25)},
		{ "PetChibiOlaf",		"Chibi Olaf",		std::make_pair(1, 5)},
		{ "PetChibiOrianna",	"Chibi Orianna",	std::make_pair(1, 5)},
		{ "PetChibiPantheon",	"Chibi Pantheon",	std::make_pair(1, 5)},
		{ "PetChibiPoppy",		"Chibi Poppy",		std::make_pair(1, 5)},
		{ "PetChibiQiyana",		"Chibi Qiyana",		std::make_pair(1, 5)},
		{ "PetChibiRakan",		"Chibi Rakan",		std::make_pair(1, 5)},
		{ "PetChibiRammus",		"Chibi Rammus",		std::make_pair(1, 5)},
		{ "PetChibiRiven",		"Chibi Riven",		std::make_pair(1, 5)},
		{ "PetChibiSamira",		"Chibi Samira",		std::make_pair(1, 5)},
		{ "PetChibiSejuani",	"Chibi Sejuani",	std::make_pair(1, 5)},
		{ "PetChibiSett",		"Chibi Sett",		std::make_pair(1, 5)},
		{ "PetChibiSivir",		"Chibi Sivir",		std::make_pair(1, 5)},
		{ "PetChibiSoraka",		"Chibi Soraka",		std::make_pair(1, 5)},
		{ "PetChibiTaliyah",	"Chibi Taliyah",	std::make_pair(1, 5)},
		{ "petchibiseraphine",	"Chibi Seraphine",	std::make_pair(1, 5)},
		{ "PetChibiSona",		"Chibi Sona",		std::make_pair(1, 5)},
		{ "PetChibiTeemo",		"Chibi Teemo",		std::make_pair(1, 5)},
		{ "PetChibiThresh",		"Chibi Thresh",		std::make_pair(1, 5)},
		{ "PetChibiTristana",	"Chibi Tristana",	std::make_pair(1, 5)},
		{ "PetChibiVayne",		"Chibi Vayne",		std::make_pair(1, 5)},
		{ "PetChibiVi",			"Chibi Vi",			std::make_pair(1, 5)},
		{ "PetChibiViego",		"Chibi Viego",		std::make_pair(1, 5)},
		{ "PetChibiYasuo",		"Chibi Yasuo",		std::make_pair(1, 5)},
		{ "petchibiyuumi",		"Chibi Yuumi",		std::make_pair(1, 5)},
		{ "PetChibiZac",		"Chibi Zac",		std::make_pair(1, 5)},
		{ "PetChibiZeri",		"Chibi Zeri",		std::make_pair(1, 5)},
		{ "petchibiyone",		"Chibi Yone",		std::make_pair(1, 5)},
		{ "PetChibiZyra",		"Chibi Zyra",		std::make_pair(1, 5)},
		{ "PetChibiZiggs",		"Chibi Ziggs",		std::make_pair(1, 5)},
		{ "PetChibiZilean",		"Chibi Zilean",		std::make_pair(1, 5)},
		{ "PetChibiZoe",		"Chibi Zoe",		std::make_pair(1, 5)},
		{ "PetChibiZed",		"Chibi Zed",		std::make_pair(1, 5)},
		{ "petchickeneggtart",	"Chicky",			std::make_pair(1, 5) },
		{ "petchip",			"Chip",				std::make_pair(1, 5) },
		{ "PetChoncc",			"Choncc",			std::make_pair(1, 51)},
		{ "PetGargoyle",		"Craggle",			std::make_pair(1, 21)},
		{ "PetSgCat",			"Dango",			std::make_pair(1, 48)},
		{ "PetDowsie",			"Dowsie",			std::make_pair(1, 36)},
		{ "PetDuckBill",		"Duckbill",			std::make_pair(1, 39)},
		{ "PetPenguKnight",		"Featherknight",	std::make_pair(1, 56)},
		{ "petfishball",		"FishBall",			std::make_pair(1, 21)},
		{ "PetFenroar",			"Fenroar",			std::make_pair(1, 33)},
		{ "PetGemTiger",		"Protector",		std::make_pair(1, 23)},
		{ "PetGhosty",			"Hauntling",		std::make_pair(1, 36)},
		{ "PetGloop",			"Gloop",			std::make_pair(1, 42)},
		{ "PetGrumpyLion",		"Furyhorn",			std::make_pair(1, 48)},
		{ "PetKoala",			"Grizzle",			std::make_pair(1, 18)},
		{ "PetSpiritFox",		"Hushtail",			std::make_pair(1, 45)},
		{ "pethundun",			"Hundun",			std::make_pair(1, 45) },
		{ "pethextechbirb",		"Hexbirb",			std::make_pair(1, 45) },
		{ "pethamster",			"Hamster",			std::make_pair(1, 45)},
		{ "PetVoidEye",			"Khat'Sai",			std::make_pair(1, 18)},
		{ "PetBigKnifeDog",		"Knife Hound",		std::make_pair(1, 18)},
		{ "PetSmolKnifeDog",	"Knife Pup",		std::make_pair(1, 18)},
		{ "PetMiniGolem",		"Runespirit",		std::make_pair(1, 22)},
		{ "PetSennaBunny",		"Melisma",			std::make_pair(1, 39)},
		{ "Petminion",			"Minion",			std::make_pair(1, 21)},
		{ "PetMiner",			"Molediver",		std::make_pair(1, 30)},
		{ "PetOwl",				"Noctero",			std::make_pair(1, 18)},
		{ "PetFairy",			"Nixie",			std::make_pair(1, 23)},
		{ "PetAkaliDragon",		"Ossia",			std::make_pair(1, 21)},
		{ "PetTurtle",			"Paddlemar",		std::make_pair(1, 42)},
		{ "PetPixiMander",		"Piximander",		std::make_pair(1, 24)},
		{ "PetElegantDragon",	"Prancie",			std::make_pair(1, 33)},
		{ "PetQiyanaDog",		"QiQi",				std::make_pair(1, 33)},
		{ "PetPegasus",			"Lightcharger",		std::make_pair(1, 42)},
		{ "petleopardgecko",	"LeopardGecko",		std::make_pair(1, 3)},
		{ "petkuroshiro",		"KuroShiro",		std::make_pair(1, 3)},
		{ "PetBallDragon",		"Poggless",			std::make_pair(1, 21)},
		{ "PetPoro",			"Poro",				std::make_pair(1, 6)},
		{ "PetDsSquid",			"Squink",			std::make_pair(1, 54)},
		{ "PetRazorBeak",		"Raptors",			std::make_pair(1, 18)},
		{ "PetTftAvatar",		"River Sprite",		std::make_pair(1, 35)},
		{ "PetGriffin",			"Silverwing",		std::make_pair(1, 37)},
		{ "petmoth",			"Silkee",			std::make_pair(1, 37) },
		{ "PetSgShisa",			"Shisa",			std::make_pair(1, 42)},
		{ "PetShark",			"Shork",			std::make_pair(1, 18)},
		{ "PetDsWhale",			"Starmaw",			std::make_pair(1, 21)},
		{ "PetUmbra",			"Umbra",			std::make_pair(1, 42)},
		{ "PetNimbleFoot",		"Nimblefoot",		std::make_pair(1, 21)},
		{ "PetSgPig",			"Fuwa",				std::make_pair(1, 31)},
		{ "PetBuglet",			"Flutterbug",		std::make_pair(1, 22)},
		{ "PetCreepyCat",		"Whisker",			std::make_pair(1, 21)},
		{ "petstyletwowarwick",	"Unb Warwick",		std::make_pair(1, 21) },
		{ "PetStyleTwoGaren",	"God-King Garen Unbound",	std::make_pair(2, 2) },
		{ "PetStyleTwoJhin",	"Dark Cosmic Jhin Unbound",	std::make_pair(2, 2) },
		{ "PetStyleTwoJinx",	"Arcane Jinx Unbound",		std::make_pair(3, 3) },
		{ "PetStyleTwoVayne",	"Project Vayne Unbound",	std::make_pair(2, 2) },
		{ "PetStyleTwoWarwick",	"Warwick Unbound",	        std::make_pair(1, 1) },
		{ "PetStyleTwoWarwick",	"Arcane Warwick Unbound",	std::make_pair(2, 2) },
		{ "petscuttlecrab",		"Scuttlecrab",		std::make_pair(1, 21) },
		{ "petscratch",			"Scratch",			std::make_pair(1, 21) },
		{ "petseaangel",		"seaangel",			std::make_pair(1, 21) },
		//Other models
		//{ "TFT_ElderDragon",	        "Elder Dragon"							 }
	};
};
